workflows:
  upload_to_testflight:
    name: Upload to TestFlight
    environment:
      vars:
        BUNDLE_ID: "com.woodtherapyuk.app"
    scripts:
      - name: Decode private key
        script: |
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 -d > AuthKey.p8
      - name: Download .ipa and upload to TestFlight
        script: |
          curl -L -o app.ipa "https://drive.google.com/uc?export=download&id=1em_LtY8eqq3mjEH95qa9_KAOVkpk4WcL"
          app-store-connect upload \
            --apiKeyId="$APP_STORE_CONNECT_KEY_ID" \
            --apiIssuer="$APP_STORE_CONNECT_ISSUER_ID" \
            --privateKey="./AuthKey.p8" \
            --bundleId="$BUNDLE_ID" \
            --path="app.ipa"
